import pandas as pd
import plotly
import plotly.express as px
import plotly.graph_objects as go

def RevenueByYear(moviesdata):
    data=moviesdata.groupby([moviesdata.release_date.dt.year]).agg({'revenue':'sum'}).sort_values(by='revenue',ascending=False)
    data.reset_index(inplace=True)
    barplot=data[data.release_date>=2000]
    fig=px.bar(x=barplot.release_date,y=barplot.revenue,labels={'x':'Year','y':'revnue'},title='Revenue Generated by Year')
    return fig

def RevenueButgetYear(moviesdata):
    go_revenue_budget=moviesdata.groupby([moviesdata.release_date.dt.year]).agg({'revenue':'sum','budget':'sum'})
    go_revenue_budget.reset_index(inplace=True)
    go_barplot=go_revenue_budget[go_revenue_budget.release_date>=2000]

    fig = go.Figure(data=[
        go.Bar(name='revenue', x=go_barplot.release_date, y=go_barplot.revenue),
        go.Bar(name='budget', x=go_barplot.release_date, y=go_barplot.budget)
    ])
    fig.update_layout(barmode='group')
    fig.update_layout(title_text='Revenue And Budget since 2000s')
    return fig

def TopMovieRating():
    pass

def Popularity():
    pass

def SearchMovieByGenre():
    pass

def TopMoviesByRevenue():
    pass